development:
  sessions:
    default:
      database: puffer_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: puffer_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: puffer_development
      hosts:
        - localhost:27017
